name: Build

on:
  push:
    branches: [master]
    tags:
      - "v*"

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
          cache: false

      - name: Force Flutter upgrade
        run: |
          flutter upgrade
          flutter --version
      
      - name: Check Flutter and Dart versions
        run: |
          flutter --version
          dart --version
      
      - name: Verify Flutter installation
        run: flutter doctor -v
      
      - name: Cache pub dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.PUB_CACHE }}
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Get dependencies
        run: |
          flutter clean
          flutter pub get --no-offline

      - name: Check format
        run: flutter format --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/keystore.jks
          echo "storeFile=keystore.jks" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties

      - name: Build Android APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error

  build-windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
          cache: false

      - name: Force Flutter upgrade
        run: |
          flutter upgrade
          flutter --version
      
      - name: Check Flutter and Dart versions
        run: |
          flutter --version
          dart --version
      
      - name: Verify Flutter installation
        run: flutter doctor -v
      
      - name: Install Visual Studio build tools
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Enable Windows Desktop Support
        run: flutter config --enable-windows-desktop

      - name: Get dependencies
        run: |
          flutter clean
          flutter pub get --no-offline

      - name: Build Windows App
        run: flutter build windows --release

      - name: Create MSIX Package
        run: |
          flutter pub add --dev msix
          flutter pub run msix:create

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: |
            build/windows/x64/runner/Release
            build/windows/x64/runner/Release/*.msix
          if-no-files-found: error

  release:
    name: Create Release
    needs: [build-android, build-windows]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app-release/app-release.apk
            windows-release/*.msix
          draft: false
          prerelease: false
          generate_release_notes: true
